{{- if .Values.backendApi.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "microservices-platform.fullname" . }}-backend-api
  namespace: {{ include "microservices-platform.namespace" . }}
  labels:
    {{- include "microservices-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "microservices-platform.fullname" . }}-backend-api
  minReplicas: {{ .Values.backendApi.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.backendApi.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.backendApi.autoscaling.targetCPUUtilization }}
{{- end }}
