apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservices-platform.fullname" . }}-frontend
  namespace: {{ include "microservices-platform.namespace" . }}
  labels:
    {{- include "microservices-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "microservices-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui
