{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservices-platform.fullname" . }}-postgres
  namespace: {{ include "microservices-platform.namespace" . }}
  labels:
    {{- include "microservices-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    {{- include "microservices-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
{{- end }}
