apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-platform-staging
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: microservices-platform
    environment: staging
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: microservices-platform
  source:
    repoURL: https://github.com/jdabid/microservices-cicd-platform.git
    targetRevision: main
    path: helm/microservices-platform
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: microservices-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
